<?php
/** @var System\Model\Layout $this */
/** @var System\Model\Collection $videos */
?>
<div class="list">
    <?php /** @var \Video\Model\Video $video */ ?>
    <?php foreach ($videos as $video): ?>
        <div class="item video-item">
            <a href="<?= $video->getUrl() ?>">
                <img class="loading" src="<?= $video->getPosterUrl() ?>" />
            </a>
            <p class="date"><?= substr($video->getDate(), 0, 10) ?></p>
            <p class="title"><?= $video->getTitle() ?></p>
        </div>
    <?php endforeach ?>
</div>