<?php
/** @var System\Model\Layout $this */
/** @var Video\Model\Video $video */
/** @var bool $isFavoriteVideo */
/** @var \System\Model\Collection $actresses */
?>
<?= $this->renderTemplate("header")  ?>
    <div class="video">
        <script>
            window.video = {
                id : <?= $video->getId() ?>
            }
        </script>
        <h1><?= $video->getTitle() ?></h1>
        <div class="detail">
            <div class="photo">
                <img src="<?= $video->getPosterUrl() ?>">
            </div>
            <div class="info">
                <div>
                    <label>番号: </label>
                    <span><?= $video->getIdentifier() ?></span>
                </div>
                <div>
                    <label>发行时间: </label>
                    <span><?= substr($video->getDate(), 0, 10) ?></span>
                </div>
                <div class="actions">
                    <a class="like<?php if($isFavoriteVideo) : ?> active<?php endif ?>"><i class="fa fa-heart"></i></a>
                    <a class="download" target="_blank" href="https://btso.pw/search/<?= $video->getIdentifier() ?>">Download</a>
                </div>
            </div>
        </div>
        <p>Actress</p>
        <div class="actresses">
            <?php /** @var \Video\Model\Actress $actress */ ?>
            <?php foreach($actresses as $actress): ?>
                <div class="actress">
                    <a href="<?= '/actress/' . $actress->getId() ?>">
                        <img class="avatar" src="<?= $actress->getAvatarUrl() ?>"/>
                    </a>
                </div>
            <?php endforeach ?>
        </div>
        <p>Video Samples</p>
        <ul class="samples">
            <?php $samples = $video->getSamples() ?>
            <?php $number = 0; ?>
            <?php /** @var \Video\Model\VideoSample $sample */ ?>
            <?php foreach ($samples as $sample) : ?>
                <li data-number="<?= $number ?>" class="item item-<?= $number ?>">
                    <img src="<?= $sample->getUrl() ?>"/>
                </li>
                <?php $number++ ?>
            <?php endforeach ?>
        </ul>
        <div id="samples-viewer">
            <button class="nav prev"><i class="fa fa-chevron-left"></i></button>
            <div class="img-wrap">
                <ul>

                </ul>
            </div>
            <button class="nav next"><i class="fa fa-chevron-right"></i></button>
            <button class="close"><i class="fa fa-close "></i></button>
        </div>
    </div>
<?= $this->renderTemplate("footer") ?>