<?php
/**
 * Created by PhpStorm.
 * User: jp.dou
 * Date: 2018/8/9
 * Time: 10:18
 */
?>
<html lang="zh-cn">
<head>
    <meta charset="utf-8"/>
    <title>Demo</title>
    <link rel="stylesheet" type="text/css" href="/skin/style.css" media="screen">
    <script type="text/javascript" src="/skin/jquery-3.3.1.min.js"></script>
    <link href="/skin/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="page-wrap">
    <div id="header">
        <ul id="nav">
            <li><a href="/videos">Videos</a></li>
            <li>
                <span>User</span>
                <ul>
                    <li><a href="/user/favorite/actresses">Favorite Actresses</a></li>
                    <li><a href="/user/favorite/videos">Favorite Videos</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="content">



