<?php
/**
 * Created by PhpStorm.
 * User: jp.dou
 * Date: 2018/8/9
 * Time: 10:18
 */
?>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>Demo</title>
    <link rel="stylesheet" type="text/css" href="/skin/style.css" media="screen">
</head>
<body>
<div class="page-wrap">
    <div id="header">
        <ul id="nav">
            <li><a href="/videos">Videos</a></li>
            <li><a href="/actresses">Actresses</a></li>
            <li><a href="/user">User</a></li>
        </ul>
    </div>
    <div id="content">



