<?php
/** @var \System\Model\Layout $this */
/** @var int $maxPage */
$page = max((int) $this->getRequest()->get('p'), 1);
$end = min($maxPage, max($page + 4, 9));
$start = max(1, min($end - 8, $page - 3));
$currentUrl = $this->getRequest()->getCurrentUrl();
?>
<div class="pagination">
    <?php if ($page != $start): ?>
        <a href="<?= $this->getUrl($currentUrl, ['p' => $page - 1]) ?>">Prev</a>
    <?php endif ?>
    <?php for ($i = $start; $i <= $end; $i++ ) : ?>
        <a class="<?= $i == $page ? 'current' : '' ?>" href="<?= $this->getUrl($currentUrl, ['p' => $i]) ?>" ><?= $i ?></a>
    <?php endfor ?>
    <?php if ($page != $end): ?>
        <a href="<?= $this->getUrl($currentUrl, ['p' => $page + 1]) ?>">Next</a>
    <?php endif ?>
</div>