<?php
/** @var App\Model\Layout $this */
/** @var \App\Model\Collection $videos */
/** @var int $pageCount */
?>
<?= $this->renderTemplate("header.phtml")  ?>
<?= $this->renderTemplate('pagination.phtml', ['maxPage' => round($videos->count() / $pageCount)]) ?>
<div class="list">
    <?php /** @var \App\Model\Video $video */ ?>
    <?php foreach ($videos as $video): ?>
        <div class="item video-item">
            <a href="<?= $video->getUrl() ?>">
                <img src="<?= $video->getPosterUrl() ?>" />
            </a>
            <p class="date"><?= substr($video->getDate(), 0, 10) ?></p>
            <p class="title"><?= $video->getTitle() ?></p>
        </div>
    <?php endforeach ?>
</div>
<?= $this->renderTemplate("footer.phtml") ?>